import functools, traceback

CRAWLING_STARTED = 'CRAWINGL_STARTED'
CRAWLING_COMPLETED = 'CRAWLING_COMPLETED'
CRAWLING_STOPPED = 'CRAWLING_STOPPED'
VISITING_URL = 'VISITING_URL'
EXCEPTION_OCCURED = 'EXCEPTION_OCCURED'
